/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
Use [Handyman_DB]
Go
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '2/3/2022', '5/22/2022', 'WA19FAFL4DA802977', 1, 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', 10);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '11/13/2021', '2/7/2022', '1G6DJ5ED7B0732820', 3, 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', 59);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Sales', '11/27/2021', '4/28/2022', 'WBAUN93599V804101', 2, 'arcu libero rutrum ac lobortis vel dapibus at diam nam', 13);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '5/21/2022', '1/12/2022', '1GKS2FEJ9CR769172', 2, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu', 89);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '9/21/2022', '3/11/2022', 'WA1WGAFP0EA956798', 2, 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 53);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '3/4/2022', '5/9/2022', '1G6DJ577880406489', 1, 'aenean sit amet justo morbi ut odio cras mi pede malesuada', 1);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '11/20/2021', '11/26/2021', 'WP0AA2A98FS454780', 1, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 81);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '10/22/2022', '7/1/2022', '1C3CDFEB3FD199372', 1, 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', 72);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Marketing', '4/4/2022', '11/7/2021', '1FTSX2B5XAE722084', 3, 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo', 53);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '4/19/2022', '7/10/2022', '1D7RW3BK5BS270747', 3, 'neque duis bibendum morbi non quam nec dui luctus rutrum', 16);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '3/2/2022', '10/22/2022', '5N1CR2MN8EC492542', 2, 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 46);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '8/11/2022', '5/19/2022', 'JN1BY1AR2EM674075', 3, 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla', 2);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '2/22/2022', '5/6/2022', '1G6AB5S31E0541880', 3, 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 94);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '11/30/2021', '1/13/2022', 'JH4CU4F6XCC717754', 2, 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 8);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '6/17/2022', '9/29/2022', '1FTSW3B54AE952311', 3, 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', 95);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '7/17/2022', '11/28/2021', '2B3CL3CG3BH833807', 2, 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra', 70);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Training', '2/23/2022', '7/23/2022', '1C4RDJEG8CC215670', 2, 'in consequat ut nulla sed accumsan felis ut at dolor quis odio', 11);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Sales', '10/28/2022', '2/4/2022', 'WAUKG78E55A538768', 2, 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 7);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '8/24/2022', '12/8/2021', '1G6DM56T950626645', 2, 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 38);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '5/25/2022', '6/19/2022', 'WAUCFAFC7FN618377', 3, 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in', 45);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Training', '9/30/2022', '5/23/2022', 'WP0CB2A86CS554353', 3, 'volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna', 86);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '8/5/2022', '8/4/2022', 'JTEBU4BF0BK483787', 1, 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 6);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Training', '11/14/2021', '3/2/2022', '3D7JV1EP3BG509845', 3, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non', 49);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '4/29/2022', '6/13/2022', '2G4GW5EV9B9797626', 1, 'sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', 52);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '3/24/2022', '8/7/2022', 'WAUEF98E86A070225', 1, 'mi integer ac neque duis bibendum morbi non quam nec', 61);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '9/17/2022', '12/12/2021', '3N1BC1AP1AL763282', 1, 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis', 100);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '4/25/2022', '6/19/2022', 'SCBLF34F84C708600', 3, 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', 68);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Marketing', '5/9/2022', '6/5/2022', 'JHMFA3F21AS872578', 2, 'consequat lectus in est risus auctor sed tristique in tempus', 24);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Engineering', '3/24/2022', '12/18/2021', '1FTSX2A59AE220622', 3, 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi', 74);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '12/14/2021', '3/23/2022', '1FTWX3B57AE679802', 2, 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi', 19);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '4/19/2022', '6/4/2022', '3D4PH9FV0AT865945', 2, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', 86);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '11/2/2021', '6/2/2022', 'WVWGU7AN7BE968673', 3, 'ut mauris eget massa tempor convallis nulla neque libero convallis eget', 97);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Sales', '7/1/2022', '10/1/2022', 'SALAG2V65EA604436', 3, 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat', 45);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '7/23/2022', '9/8/2022', 'JH4KC1F76EC726847', 3, 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', 91);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '11/8/2021', '4/26/2022', '5J8TB4H7XGL408192', 3, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat', 59);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Marketing', '10/26/2022', '3/23/2022', 'WAUKD98P69A870066', 1, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 64);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '6/2/2022', '1/8/2022', 'WBAAV53491F535437', 2, 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius', 94);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '9/11/2022', '9/29/2022', 'WAUHFAFLXFN127615', 1, 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 62);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '4/8/2022', '7/29/2022', '1G6DC1E32C0934878', 3, 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea', 76);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Engineering', '1/16/2022', '8/4/2022', '19XFA1E32BE000978', 3, 'hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat', 17);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '12/19/2021', '11/28/2021', 'WAUFFBFL2BA117062', 2, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 22);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Engineering', '9/13/2022', '9/2/2022', '1G6KD57916U659319', 2, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas', 97);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '4/20/2022', '2/28/2022', '1G6DH8E5XD0460076', 1, 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 34);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Sales', '11/22/2021', '3/3/2022', '3VW8S7AT4FM270916', 2, 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 26);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '2/15/2022', '2/1/2022', '4T1BF3EK1AU198676', 2, 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', 43);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '10/6/2022', '12/26/2021', '5N1AR2MM1FC971515', 2, 'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate', 90);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '10/1/2022', '8/27/2022', '1D7RB1CT7BS147068', 1, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', 49);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '4/3/2022', '10/1/2022', '3MZBM1K72FM050334', 1, 'id sapien in sapien iaculis congue vivamus metus arcu adipiscing', 47);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '4/6/2022', '5/5/2022', '1GD21XEG5FZ434466', 3, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', 92);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '3/29/2022', '11/29/2021', 'WBAUL7C56AV548580', 2, 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', 32);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Marketing', '6/14/2022', '1/6/2022', 'WUADUAFG9BN593270', 2, 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 6);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '5/23/2022', '9/16/2022', '2HNYD2H65CH181280', 3, 'in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', 44);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '7/27/2022', '8/26/2022', 'WBA8Z5C51FG335259', 1, 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris', 21);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '1/16/2022', '1/19/2022', 'JH4NA12665S074382', 2, 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi', 17);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '2/9/2022', '9/9/2022', 'JTHBL5EF8F1879940', 3, 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet', 100);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '6/2/2022', '7/26/2022', 'WA1YD64BX3N689679', 1, 'sem praesent id massa id nisl venenatis lacinia aenean sit', 39);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '10/2/2022', '12/1/2021', 'WA1BY94L17D027974', 3, 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', 71);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Sales', '9/8/2022', '7/27/2022', '4T1BF3EK3BU626457', 1, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 89);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '8/22/2022', '5/4/2022', 'WBS3R9C50FF302367', 1, 'lorem id ligula suspendisse ornare consequat lectus in est risus', 94);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '6/22/2022', '4/20/2022', '1FTSX2B51AE657366', 1, 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 68);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '9/24/2022', '12/21/2021', '1G6AS5SX5E0814385', 2, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 43);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '9/5/2022', '4/20/2022', 'JA32X2HU3BU002133', 2, 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 24);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '10/28/2022', '5/30/2022', '1N6AA0CC0AN060143', 3, 'quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 85);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '10/11/2022', '2/9/2022', '2HNYD28897H092223', 1, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum', 54);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Training', '3/24/2022', '4/17/2022', '1D7RE3BK4BS897555', 3, 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id', 36);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '8/5/2022', '10/4/2022', 'JN8AE2KP4C9683417', 1, 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', 65);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Engineering', '10/22/2022', '2/27/2022', '3VW1K7AJ3EM896391', 2, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 61);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '1/14/2022', '7/25/2022', 'WAUAFAFH3CN142076', 3, 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci', 9);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '12/23/2021', '12/11/2021', '1G6AB5RA9E0526404', 1, 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', 42);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Engineering', '9/8/2022', '12/28/2021', 'JTDZN3EU3E3164113', 3, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin', 75);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Training', '1/29/2022', '8/1/2022', '2C3CCAKT7CH473626', 1, 'eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis', 19);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '10/4/2022', '1/23/2022', '1G4GD5GGXAF796950', 3, 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', 34);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '10/24/2022', '1/27/2022', 'WAUML44E06N527731', 1, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu', 1);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '7/14/2022', '3/1/2022', 'KL4CJGSB2DB241323', 3, 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna', 90);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Engineering', '10/10/2022', '12/27/2021', '5UMDU93457L345411', 3, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin', 56);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '5/13/2022', '6/8/2022', '1G6AA5RX5D0575248', 3, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 100);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '8/31/2022', '12/23/2021', '1GTC5LF90B8226226', 2, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', 72);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '3/24/2022', '8/9/2022', 'WBAVB17506N411611', 2, 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 66);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Marketing', '8/6/2022', '11/27/2021', '1G4GE5ED7BF123542', 3, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh', 53);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '12/14/2021', '12/30/2021', '1LNHL9DK1DG405156', 1, 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi', 9);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Support', '5/15/2022', '11/2/2021', 'SCBCR7ZA5AC879554', 1, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec', 85);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '6/2/2022', '9/17/2022', '1N6AF0LX2FN310817', 3, 'suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 53);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Services', '11/20/2021', '10/28/2022', 'WBAEB535X9C930825', 1, 'quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 64);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Marketing', '5/10/2022', '7/29/2022', 'KMHTC6AD4EU852808', 2, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', 68);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Legal', '11/22/2021', '12/2/2021', '1VWAP7A36EC923619', 2, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor', 8);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Marketing', '5/27/2022', '6/19/2022', 'KM8NU4CC4CU160575', 2, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 52);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Training', '3/20/2022', '6/13/2022', 'WA1AY94L28D900595', 3, 'amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', 21);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '5/19/2022', '9/16/2022', '3C3CFFHH2DT575786', 2, 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 8);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Sales', '5/7/2022', '4/5/2022', 'YV4902NB5F1639052', 2, 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', 54);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '3/27/2022', '5/1/2022', 'W04GU5GC0B1285287', 3, 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', 52);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '11/12/2021', '4/19/2022', 'WVWAA7AJ5CW123540', 2, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 73);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Training', '5/15/2022', '8/28/2022', 'WAUUL68E45A831236', 3, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 59);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '10/29/2022', '7/26/2022', 'ZFBCFADH7EZ573324', 3, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', 61);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Engineering', '3/13/2022', '5/8/2022', '1N6AA0CC4BN724235', 3, 'sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', 16);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Sales', '3/29/2022', '12/9/2021', '3MZBM1K77FM065105', 2, 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 19);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Research and Development', '9/23/2022', '2/23/2022', 'WP0CB2A83FK165545', 3, 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 14);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Accounting', '6/9/2022', '10/2/2022', 'WAUDFBFCXCN835752', 3, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 51);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Human Resources', '7/19/2022', '5/28/2022', 'TRUDD38J981477431', 1, 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 34);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Product Management', '10/25/2022', '3/7/2022', '1G6AF5SX4E0769069', 2, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu', 42);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '3/23/2022', '4/12/2022', 'WBADT33421G946549', 3, 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat', 5);
insert into [Request].[task] (tas_title, tas_date_started, tas_date_finished, tas_duration, tas_status, tas_description, tas_service_id) values ('Business Development', '3/23/2022', '4/12/2022', 'WBADT33421G946549', 3, 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat', 5);
