
USE [master]
GO

/****** Object:  Database [HandymanDB]    Script Date: 2022/06/17 19:24:35 ******/
DROP DATABASE [HandymanDB]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HandymanDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HandymanDB] SET ANSI_NULL_DEFAULT ON
GO

ALTER DATABASE [HandymanDB] SET ANSI_NULLS ON
GO

ALTER DATABASE [HandymanDB] SET ANSI_PADDING ON
GO

ALTER DATABASE [HandymanDB] SET ANSI_WARNINGS ON
GO

ALTER DATABASE [HandymanDB] SET ARITHABORT ON
GO

ALTER DATABASE [HandymanDB] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [HandymanDB] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [HandymanDB] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [HandymanDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [HandymanDB] SET CURSOR_DEFAULT  LOCAL
GO

ALTER DATABASE [HandymanDB] SET CONCAT_NULL_YIELDS_NULL ON
GO

ALTER DATABASE [HandymanDB] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [HandymanDB] SET QUOTED_IDENTIFIER ON
GO

ALTER DATABASE [HandymanDB] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [HandymanDB] SET  DISABLE_BROKER
GO

ALTER DATABASE [HandymanDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [HandymanDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [HandymanDB] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [HandymanDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [HandymanDB] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [HandymanDB] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [HandymanDB] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [HandymanDB] SET RECOVERY FULL
GO

ALTER DATABASE [HandymanDB] SET  MULTI_USER
GO

ALTER DATABASE [HandymanDB] SET PAGE_VERIFY NONE
GO

ALTER DATABASE [HandymanDB] SET DB_CHAINING OFF
GO

ALTER DATABASE [HandymanDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [HandymanDB] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [HandymanDB] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [HandymanDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HandymanDB] SET  READ_WRITE
GO


/****** Object:  Database [HandymanDB]    Script Date: 2022/06/17 19:24:35 ******/
CREATE DATABASE [HandymanDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HandymanDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HandymanDB_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HandymanDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HandymanDB_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

GO

--Syntax Error: Expected DEFAULT_FULLTEXT_LANGUAGE but encountered CATALOG_COLLATION instead.
--
--/****** Object:  Database [HandymanDB]    Script Date: 2022/06/17 19:24:35 ******/
--CREATE DATABASE [HandymanDB]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'HandymanDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HandymanDB_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'HandymanDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HandymanDB_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
-- WITH CATALOG_COLLATION = DATABASE_DEFAULT

GO


ALTER DATABASE [HandymanDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  

GO

--Syntax Error: Incorrect syntax near ACCELERATED_DATABASE_RECOVERY.
--
--ALTER DATABASE [HandymanDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  



GO
